development:
  host: localhost
  database: testapp_development

test:
  host: localhost
  database: testapp_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['mongodb://<user>:<password>@staff.mongohq.com:10069/app1214556'] %>
  
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
